spring:
  application:
    name: Hello JMS
  activemq:
    broker-url: tcp://localhost:61616
    user: user
    password: user

server:
  port: 8088

hellojms:
  messaging:
    queues:
      person: persons
